spring.datasource.url=jdbc:mysql://localhost:3306/quantitydb
spring.datasource.username=
spring.datasource.password=


spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=profile,email
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
