spring.datasource.url=jdbc:mysql://localhost:3306/quantitydb
spring.datasource.username=
spring.datasource.password=


spring.security.oauth2.client.registration.google.client-id=1069868916198-foeh7ndk6jmiflt8op925consi65hnkf.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
